version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartpx_api
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=smarpx
      - DB_USERNAME=root
      - DB_PASSWORD=smartpx24
    networks:
      - smartpx_net
    depends_on:
      - db


  db:
    image: mysql:8.0
    container_name: smartpx_db
    environment:
      MYSQL_ROOT_PASSWORD: smartpx24
      MYSQL_DATABASE: smartpx_db
      MYSQL_USER: smartpx_user
      MYSQL_PASSWORD: smartpx24
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - smartpx_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p smartpx24"]
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - smartpx_net
    depends_on:
      - db

  
networks:
  smartpx_net:
    driver: bridge

volumes:
  db_data:
